'use strict';

// Cross-language regression lock. `test/fixtures/nb_golden.json` is generated by
// `scripts/gen-nb-golden.js`; the Dart classifier
// (`app/lib/capture/naive_bayes.dart`) loads the same file and must reproduce
// the same numbers. If this file goes red, either the tokenizer/scoring changed
// (and Dart has to change with it) or something drifted — regenerating the
// fixture to make the test pass again is the one thing you must not do.

const test = require('node:test');
const assert = require('node:assert/strict');

const nb = require('../src/lib/nb');
const golden = require('./fixtures/nb_golden.json');

const EPS = 1e-6;

test('golden ① 夹具自身是完整的', () => {
  assert.ok(golden.strings.length >= 20, `至少 20 条样本串，实得 ${golden.strings.length}`);
  assert.equal(golden.tokens.length, golden.strings.length);
  assert.equal(golden.predictions.length, golden.strings.length);
  assert.deepEqual(golden.extras, ['m:美团', 'dir:expense']);
  assert.equal(golden.training.length, 6);
  assert.ok(golden.model.totalDocs > 0 && golden.model.vocab > 0);
});

test('golden ② tokenize 逐项完全复现（不允许任何误差）', () => {
  golden.strings.forEach((s, i) => {
    assert.deepEqual(
      nb.tokenize(s, golden.extras),
      golden.tokens[i],
      `strings[${i}] = ${JSON.stringify(s)} 的分词结果变了`,
    );
  });
});

test('golden ③ 用 training 重新训练，得到与夹具一致的模型', () => {
  const model = nb.emptyModel();
  for (const t of golden.training) nb.learn(model, nb.tokenize(t.text), t.label);

  // version 不在跨语言契约内（服务端由端点管，Dart 端 learn 自增），只比这三项。
  // 比【序列化后】的形态：契约是那份 JSON，而 counts 在内存里是无原型对象
  // （防 __proto__ 污染），直接 deepEqual 会被原型差异卡住。
  assert.deepEqual(JSON.parse(JSON.stringify(model.classes)), golden.model.classes);
  assert.equal(model.vocab, golden.model.vocab);
  assert.equal(model.totalDocs, golden.model.totalDocs);
  assert.equal(model.vocab, nb.vocabOf(model));
});

test('golden ④ predict 的 label、顺序完全一致，概率误差 ≤ 1e-6', () => {
  const model = nb.parse(JSON.stringify(golden.model));
  golden.strings.forEach((s, i) => {
    const got = nb.predict(model, nb.tokenize(s, golden.extras));
    const want = golden.predictions[i];
    assert.equal(got.length, want.length, `strings[${i}] 的类别数变了`);
    got.forEach((g, k) => {
      assert.equal(g.label, want[k].label, `strings[${i}] 第 ${k} 名的 label 变了：${JSON.stringify(s)}`);
      assert.ok(
        Math.abs(g.p - want[k].p) <= EPS,
        `strings[${i}] ${g.label} 的 p 偏差 ${Math.abs(g.p - want[k].p)} > ${EPS}：${JSON.stringify(s)}`,
      );
    });
    const sum = got.reduce((a, x) => a + x.p, 0);
    assert.ok(Math.abs(sum - 1) < 1e-12, `strings[${i}] 概率和不是 1`);
  });
});

test('golden ⑤ extras 是故意 OOV 的：漏掉 OOV 规则就一定对不上', () => {
  const model = nb.parse(JSON.stringify(golden.model));
  const vocab = nb.vocabulary(model);
  for (const e of golden.extras) {
    assert.ok(!vocab.has(e), `${e} 必须不在词表里，否则这道锁就锁不住 OOV 规则`);
  }
  // 带不带这两个 extras，结果必须一模一样
  golden.strings.forEach((s, i) => {
    const withExtras = nb.predict(model, nb.tokenize(s, golden.extras));
    const without = nb.predict(model, nb.tokenize(s));
    assert.deepEqual(withExtras, without, `strings[${i}] 受到了 OOV extras 的影响`);
  });
});
